### ISSUE TITLE
The build server is not generating the pdfium.dll

### ISSUE THREAD

**Issue by vijayanand2k** [pvginkel/PdfiumBuild#1]
The build server https://assendelft.webathome.org/Pdfium/ is not generating pdfium.dll from mid of May 2017. Could you please resolve the issue?

**Comment by pvginkel** [comment]
Thanks for reporting this. It's not as bad as you indicated, but it's been out for a while.

I've done a few things:

* The problem was caused by Jenkins running as a system account. This was confusing Python for some reason. This has been fixed and the builds are running again (it's running at the moment and should complete in a while);
* I've replaced the directory browser with something else which is a bit more palatable. It now shows whether the builds succeeded and has links directly into the generated DLL's and build log.

I hope this helps.

**Comment by vijayanand2k** [comment]
Thank you so much! Really appreciated!
